### ISSUE TITLE
typo on blacklist-binance.json

### ISSUE THREAD

**Issue by ketaeishi** [iterativv/NostalgiaForInfinity#123]
In /config/blacklist-binance.json there is a typo probs line 9 : `".*(_PREMIUM|BEAR|BULL|DOWN|HALF|HEDGE|UP|[1235][SL])/.*",`
It should be `"(_PREMIUM|BEAR|BULL|DOWN|HALF|HEDGE|UP|[1235][SL])/.*",`

**Comment by abc112116** [comment]
it's a regex. `.*(_PREMIUM|BEAR|BULL|DOWN|HALF|HEDGE|UP|[1235][SL])` mean anything followed by those words in (...) will be included. Without  `.*` It means only those names. 
Since we need to blacklist every coin with *up and *down on Binance it would be `".*(UP|DOWN|)/.*"` anything else are a relic of other exchange which doesn't impact anything. 

Are you having a problem with those?

**Comment by hippocritical** [comment]
bull/bear pairs were not filtered out

**Comment by BillGatesIII** [comment]
I just checked with regex101.com and it seems to be working correct.

https://regex101.com/r/4qeSkc/1
