### ISSUE TITLE
A question about the volume of trades per day

### ISSUE THREAD

**Issue by ed96win** [iterativv/NostalgiaForInfinity#154]
First, I wanna thank you for developing this. amazing job.

I want to know if its normal for this strategy to create [only] 3~4 trades per day. (and most of the times they happen at midnight [GMT +3:30]).
I'm asking this cuz KuCoin API has been having problems recently (throwing 429 - ratelimits) and I don't know if this is because of that problem, or its just the logic of this strategy.

by saying [only] 3~4 trades a day I'm not undervaluing it or expecting it to blindly buy anything that's on the market. I'm just curious. I also know that the market changes every day and neither of these variables stays still.

the configuration is set to have 6 trades max, with unlimited stake; and it is set to get 80 PairLists while blacklisting the tokens that are mentioned in the FAQ; and my balance is about 600 USD. using the latest release of your amazing strategy and the latest stable release of freqtrade.

**Comment by geekybrick** [comment]
I'm currently running NFIX with suggested settings on Kraken and getting 1.5 trades per day on average with decent results (8-10% monthly, which is very good but not quite the insane results presented in the backtests here on GitHub).

I realize that market conditions change constantly but still I can't help wondering whether this is expected behavior or it has something to do with, e.g., rate limiting on Kraken.

@iterativv thanks for your great work!

**Comment by iterativv** [comment]
Yes, depends on the exchange, pairs, market conditions and other factors. But that is one of the main objective, if possible to increase the number of trades per day.
