### ISSUE TITLE
Performance issue with strategy

### ISSUE THREAD

**Issue by oldgitdaddy** [iterativv/NostalgiaForInfinity#156]
Hi everyone, I run NFI on a raspberry 3 on docker. Freqtrade suggests that vectors instead of loops should be used in the strategy. Any help is appreciated. Cheers!

Original issue on freqtrade github is here: https://github.com/freqtrade/freqtrade/issues/5917

**Comment by eSeR1805** [comment]
1. we don't recommend running NFI on RPIs due to limited resources(maybe 4 can handle it better)
2. not sure why you need to run through docker since you're already under linux os. docker just adds overhead
3. most indicators are vectorised and we've dropped almost all looped ones. the problem is the sheer amout of indicators and extra logic used by the strategy
TLDR: NFI is likely not going to get any lighter than this. It's right after 2 refactors so it's probably only going to get heavier from here

**Comment by oldgitdaddy** [comment]
Ok. Good to know. I tried it with the raspberry without docker, but performance is still disappointing. Moved to VPS. Issue closed.
