### ISSUE TITLE
stoploss not working in dry-run 

### ISSUE THREAD

**Issue by taygun08** [iterativv/NostalgiaForInfinity#456]
I noticed that it continued to trade even though it reached the stoploss  

![image](https://github.com/user-attachments/assets/7b35a282-697f-4bae-8881-e9b6cbdad832)

**Comment by iterativv** [comment]
Hi, yes, right NFI there is de-risk. For futures if reach 60% down on user stake, it will exit all stake, but the min. Then continue grinding in order to recover it.

NFI is using custom calculations for profits, stops and so on. Because the ones provided are not accurate for the while trade, if there are partial exits.

Also, that BLZ will get delisted, that's why the drop too.
